// code by jph
package ch.alpine.ascona.crv.clt;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Rectangle;

import ch.alpine.ascony.ren.ColorPairs;
import ch.alpine.ascony.ren.ColorStrokeIndexed;
import ch.alpine.ascony.ren.PathRender;
import ch.alpine.bridge.fig.Show;
import ch.alpine.bridge.fig.Showable;
import ch.alpine.bridge.fig.plt.ListLinePlot;
import ch.alpine.bridge.gfx.GeometricLayer;
import ch.alpine.sophis.crv.d2.Curvature2D;
import ch.alpine.sophus.clt.Clothoid;
import ch.alpine.sophus.clt.ClothoidBuilder;
import ch.alpine.sophus.clt.ClothoidBuilders;
import ch.alpine.sophus.clt.LagrangeQuadraticD;
import ch.alpine.sophus.lie.so2.ArcTan2D;
import ch.alpine.tensor.RealScalar;
import ch.alpine.tensor.Scalar;
import ch.alpine.tensor.Tensor;
import ch.alpine.tensor.Tensors;
import ch.alpine.tensor.alg.Subdivide;
import ch.alpine.tensor.api.TensorUnaryOperator;
import ch.alpine.tensor.img.ColorDataIndexed;
import ch.alpine.tensor.img.ColorDataLists;
import ch.alpine.tensor.lie.rot.AngleVector;
import ch.alpine.tensor.sca.Clips;
import ch.alpine.tensor.sca.Round;

/** compares clothoids generated by analytical integral and lebeque integral
 * and their curvature: the analytical clothoid yields linear curvature */
class ClothoidDemo extends ClothoidBaseDemo {
  private static final Tensor DOMAIN = Subdivide.of(0.0, 1.0, 200);
  private static final Tensor ARROWS = Subdivide.intermediate_increasing(Clips.unit(), 5);
  private static final ColorDataIndexed COLOR_DATA_INDEXED = //
      ColorDataLists._097.cyclic().deriveWithAlpha(192);
  private final ClothoidBuilder[] clothoidBuilders = new ClothoidBuilder[] { //
      ClothoidBuilders.SE2_ANALYTIC.clothoidBuilder(), //
      ClothoidBuilders.SE2_LEGENDRE.clothoidBuilder() };

  public ClothoidDemo() {
    setControlPointsSe2(Tensors.fromString("{{2,0,0},{-2,0,0}}"));
  }

  @Override // from RenderInterface
  public void render(GeometricLayer geometricLayer, Graphics2D graphics) {
    Tensor control = getGeodesicControlPoints();
    Tensor start = control.get(0);
    Tensor mouse = control.get(1);
    // ---
    {
      int index = 0;
      ColorStrokeIndexed colorStrokeIndexed = new ColorStrokeIndexed(COLOR_DATA_INDEXED, new BasicStroke(1.5f));
      for (ClothoidBuilder clothoidBuilder : clothoidBuilders) {
        Clothoid clothoid = clothoidBuilder.curve(start, mouse);
        Tensor points = DOMAIN.maps(clothoid);
        new PathRender(colorStrokeIndexed.getColorStroke(index), points, false).render(geometricLayer, graphics);
        manifoldDisplay().showPoints(ColorPairs.INTERMEDIATE, RealScalar.ONE, ARROWS.maps(clothoid)) //
            .render(geometricLayer, graphics);
        ++index;
      }
    }
    Show show = new Show();
    show.setShowLabel("Curvature Comparison");
    int index = 0;
    ColorStrokeIndexed colorStrokeIndexed = new ColorStrokeIndexed(COLOR_DATA_INDEXED, new BasicStroke());
    TensorUnaryOperator tuo = v -> v.extract(0, 2);
    for (ClothoidBuilder clothoidBuilder : clothoidBuilders) {
      Clothoid clothoid = clothoidBuilder.curve(start, mouse);
      Tensor points = DOMAIN.maps(clothoid);
      Color color = COLOR_DATA_INDEXED.getColor(index);
      new PathRender(colorStrokeIndexed.getColorStroke(index), points, false).render(geometricLayer, graphics);
      graphics.setColor(color);
      {
        Scalar angle = ArcTan2D.of(clothoid.apply(RealScalar.of(1e-8)));
        graphics.drawString(angle.maps(Round._5).toString(), 0, 40 + index * 20);
        graphics.draw(geometricLayer.toLine2D(AngleVector.of(angle)));
      }
      {
        LagrangeQuadraticD lagrangeQuadraticD = clothoid.curvature();
        Scalar angle = lagrangeQuadraticD.head();
        graphics.draw(geometricLayer.toLine2D(AngleVector.of(angle).multiply(RealScalar.of(2))));
      }
      Tensor string = Curvature2D.INSTANCE.string(tuo.slash(points));
      Showable showable = show.add(ListLinePlot.of(DOMAIN, string));
      showable.setLabel(clothoid.toString());
      ++index;
    }
    Dimension dimension = geometricComponent().getSize();
    show.render_autoIndent(graphics, new Rectangle(dimension.width / 2, 0, dimension.width / 2, dimension.height));
  }

  static void main() {
    new ClothoidDemo().runStandalone();
  }
}
