name: java
on:
  push:
    paths:
      - '**'
  pull_request:
    branches:
      - main
    types:
      - opened
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: mvn install tensor 106
        working-directory: .
        run: |
          cd ..
          git clone https://github.com/datahaki/tensor.git
          cd tensor
          git checkout v106
          mvn clean install -DskipTests=true
          
      - name: mvn install sophus 010
        working-directory: .
        run: |
          cd ..
          git clone https://github.com/datahaki/sophus.git
          cd sophus
          mvn clean install -DskipTests=true
          
      - name: mvn install bridge 035
        working-directory: .
        run: |
          cd ..
          git clone https://github.com/datahaki/bridge.git
          cd bridge
          git checkout v035
          mvn clean install -DskipTests=true
          
      - name: mvn test
        working-directory: .
        run: xvfb-run --auto-servernum mvn test -B
