name: mvn test with JDK 17
on:
  push:
    paths:
      - '**'
jobs:
  os_matrix:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: mvn install tensor
        working-directory: .
        run: |
          cd ..
          git clone https://github.com/datahaki/tensor.git
          cd tensor
          mvn clean install -DskipTests=true
      - name: mvn install sophus
        working-directory: .
        run: |
          cd ..
          git clone https://github.com/datahaki/sophus.git
          cd sophus
          mvn clean install -DskipTests=true
      - name: mvn install bridge
        working-directory: .
        run: |
          cd ..
          git clone https://github.com/datahaki/bridge.git
          cd bridge
          mvn clean install -DskipTests=true
      - name: mvn test
        working-directory: .
        run: mvn test -B
